In [7]:
import os
import cv2
import numpy as np
import xml.etree.ElementTree as ET

from constants import *
from functions import show, put_labels

In [2]:
import skimage
import numpy as np
import cv2
from load import *
from extract import *

#loading regions from images from the PASCAL VOC training data.
#images_regns is a list of dicts with each dict having image name as key and 
#corresponding 100 region boxes as values sorted in decreasing order of perspective regions.
images_regns = load_regions()

print "\n\nRegions Loaded by Selective Search."

ground_truth = load_ground_truth(images_regns)
print "Loaded ground truth...\n"
#ground_truth is list of objects in each image 
#each element in list contains image name and list of dicts of object class and corresponding boxes.

#Get positive and negetive features of image boxes for each class.
[pos,neg] = get_positve_negative(images_regns,ground_truth)

loading every image's regions for train


KeyboardInterrupt: 

In [6]:
img = cv2.imread(folder_test+'/000658.jpg')
print len(img)
print len(img[0])
print len(img[0][0])
print img.shape
print img[374]
print img[374][499]

# color = (0, 255, 0)
# thickness = 2
# cv2.rectangle(img, (1,1), (499,299), color, thickness)
show(img)

375
500
3
(375, 500, 3)
[[42 43 41]
 [43 44 42]
 [45 46 44]
 ..., 
 [81 80 82]
 [76 75 77]
 [69 68 70]]
[69 68 70]


In [2]:
def filter_features(fd):
    return [f for f in fd if len(f)==2048]

In [3]:
class_positives = np.load('cat_vs_dogs_positives.npy')
#class_negatives = np.load('cat_vs_dogs_negatives.npy')

#get dicts from numpy array
class_positives = class_positives[()]

In [5]:
dog = class_positives['dog']
cat = class_positives['cat']
print 'before filtering',len(dog),len(cat)
dog = filter_features(dog)
cat = filter_features(cat)
print 'after filtering',len(dog),len(cat)

['sheep',
 'horse',
 'bicycle',
 'bottle',
 'cow',
 'sofa',
 'dog',
 'bus',
 'cat',
 'person',
 'train',
 'boat',
 'aeroplane',
 'car',
 'pottedplant',
 'tvmonitor',
 'chair',
 'bird',
 'diningtable',
 'motorbike']